form.yml
template/script.sh.erb

Addresses #12.
By adding an optional delimited field to the `form.yml` value for `version` we can replace the loaded version of R at RStudio Server start time.
One issue that I had is that when I started up a 3.4.2 and 3.5.0 concurrently I had an error logging into the 3.5.0 instance. This only happened once and I have not been able to duplicate it, but it seems like there is some race condition in that particular workflow.

Choose a non-standard version of R for use with RStudio

---

Singularity
form.yml
template/script.sh.erb

This commit removes the requirement for using `proot` to create private /tmp spaces. Instead a Singularity container is used which mounts RStudio and its dependencies from the host, plus overrides the mount for /tmp using a new tmp dir rooted in PBSTMP. The Singularity container is as simple as can be requiring only the installation of `which` over the base CentOS 7. Since R or RStudio are not installed in the image then the image should not require a rebuild in the event of changes to RStudio.
~~The path to the image is currently in my home directory, and needs to be moved to a system directory, or the WIAG user's home. Also naming the image something slightly more useful than `centos7.simg` like `rstudio_launcher_centos7.simg` may be useful.~~
Heechang has installed the image in a …

Singularity based RStudio

---

CHANGELOG.md
template/script.sh.erb

In the next environment for Owens RStudio stopped working. This is the result of the environment not being properly exported to the rsession wrapper.

Fix for environment not being properly exported to rsession wrapper

---

template/script.sh.erb

Adding the texlive (texlive/2018) module to load so that users can create and save Markdown files. I verified that it works, and will add an image of it not working shortly.

add texlive (LaTeX) module for saving pdf mardown files

---

.gitlab-ci.yml

This is identical to changes we made for main ondemand repo. Without this changes we will get lots of puppet errors in dev when packages exist in latest but not ci.

Always push packages to CI repo

---

form.js
form.yml

The new `app_rstudio_server/3.6.3` loads CUDA modules, so this PR allows users to choose GPU nodes, if that version is selected.
```
module show app_rstudio_server/3.6.3
...
depends_on("gnu/9.1.0","mkl/2019.0.3","rstudio/1.2.5001","R/.3.6.3","texlive","cuda/10.1.168")
```

add the ability to choose GPU nodes, but only for version 3.6.3

---

template/before.sh.erb
template/script.sh.erb

simplify tutorial toggles because the RStudio classes are similar in functionality but slightly different in strategy. This way we
utilize SINGULARITY_HOME instead of mounting HOME to the tutorial directory. This way any class/tutorial can simply specify a different SINGULARITY_HOME to contain their rsession files.

simplify tutorial toggles

---

template/script.sh.erb

Specify the TZ to get rid of warnings like this below because we're mounting `/etc/localtime` directly.
```
> Sys.timezone()
Failed to create bus connection: No such file or directory
Warning: Your system is mis-configured: ‘/etc/localtime’ is not a symlink
Warning: It is strongly recommended to set envionment variable TZ to ‘America/New_York’ (or equivalent)
```

specify TZ to get rid of warnings

---

template/script.sh.erb

there is some issue in binding all of etc /etc (which this image does)
and so we dropped it. only we need all of /etc so this re-enables it.
the isse is fixed if we set HOME=SINGULARITY_HOME so users in tutorials
and classes can create a ~/.rstudio directory (which before wouldn't work
because HOME was still being evaluated as the actual home which didn't
exist in the container).

use centos7 img and force home=sing_home

---

form.js

Add a check in toggle_visibility to be sure you found the element you are toggling.  This can come up when a different site (say stat.osc.edu) overrides the form and there is no `include_tutorials` form item and therefore no html element to toggle.

add a check in toggle_visibility

---

form.js
form.yml
submit.yml.erb

add pitzer expansion
- change capitalize function to capitalize_words to change 'pitzer-exp'
to PitzerExp (to access the data attributes)
- add option-for attributes to the node types because hugemem is not
available on pitzer-exp and largemem is _only_ available on pitzer-exp
- lastly obviously, submit.yml.erb has to change to accomidate slurm
options and torque options.
Again, borrowed heavily work done in jupyter: https://github.com/OSC/bc_osc_jupyter/pull/48

Add pitzer exp

---

form.yml
packaging/ondemand-bc_osc_rstudio_server.spec
submit.yml.erb

Bugfixes for v0.15.0 (Pitzer expansion merging into Pitzer) while we test.

0.15 bugfixes

---

form.yml
submit.yml.erb

add owens-slurm cluster to begin migrating owens to Slurm. With this addition we determine native arguments based on the `cluster.job.adapter` so this will work when migrated fully to Slurm and owens-slurm turns into just owens.

add owens-slurm cluster to begin migrating owens to Slurm

---

form.yml
submit.yml.erb

I noticed this while working on lmod stuff, that we still have `owens-slurm` as an option in the form. This removes that and removes all the torque related stuff in the submit.yml.erb.

remove owens-slurm cluster and torque related configs

---

info.md.erb
template/script.sh.erb

Mutually exclusive with #53  this allows users to `module load` from within the Rstudio server's terminal windows.

enable loading modules in r-studio with instructions

---

template/script.sh.erb

rsync class materials if the env variable exists because to help the ease of use for some classrooms & students that are not technically saavy enough to copy the materials themselves.

rsync class materials if the env variable exists

---

form.js
form.yml.erb

Fixes #65
Because I removed logic to look at cluster + node type, we either have to do the lowest possible cluster (owens) or just set on some low value. I opted to just max out core count for Kubernetes at 10, but can easily adjust to max the max the max for smallest nodes which are Owens.

Ensure core count behavior works with Kubernetes

---

template/script.sh.erb

classrooms should only bind the directories they have access to.  This means classrooms can work out of the box, while PIs create the directories in the project space after the fact.

classrooms only bind the directories they have access to

---

form.js

I saw this in javascript console when using `local` directory forms like for class.osc.edu:
```
new:695 Uncaught TypeError: Cannot read property 'includes' of undefined
at toggle_email_on_started (new:695)
at new:829
at new:840
```

Avoid errors for class.osc.edu

---

submit.yml.erb

This is the new memory ratio with hyperthreading enabled.  This is rounded down slightly:
```
NAME           CLUSTER   CPU   MEMORY
kubeworker01   pitzer    96    394620128Ki
kubeworker02   pitzer    96    394620124Ki
kubeworker03   pitzer    96    394620120Ki
kubeworker04   owens     56    131761240Ki
kubeworker05   owens     56    131761240Ki
kubeworker06   owens     56    131761232Ki
kubeworker07   owens     56    131761232Ki
[root@kubecontroller ~]# echo "394620128 / 1024 / 96" | bc -l
4014.28352864583333333333
[root@kubecontroller ~]# echo "131761232 / 1024 / 56" | bc -l
2297.73353794642857142857
```

Adjust memory ratio for K8 jobs

---

template/script.sh.erb

use a regex that accomidates all versions. There's currently a bug where old R versions actually evaluate to being > 4.1.

use a regex that accomidates all versions

---

CHANGELOG.md
form.yml.erb

fix min & max for ascend along with the form label for R version

fix min & max for ascend along with the form label for R version

---

form.yml.erb

Significant downtime for c18 has been pushed out a few months. Now that we need to make updates, it's time to revert this.
Reverts OSC/bc_osc_rstudio_server#110

Revert "rm c18 options"

---

form.yml.erb
template/script.sh.erb

We ran into an issue with the singularity update (below) that is un-resolvable, at least on RHEL 7. 
https://github.com/apptainer/apptainer/issues/297
So this change is to use `bwrap` to get a new mount namespace and do not use any user namespaces.
This also removes the unused `4.2.1-gnu11.2` option just because it's not required (duplicate of 4.2.1).

Use bwrap instead of singularity

---

form.yml

cap cardinal cores so folks can actually schedule more than the last minimum setting.

cap cardinal cores

---

form.yml
submit.yml.erb

cleanup this form and submit by removing `owens` entirely (not sure if there are still k8s nodes that are owens) and removing the ability to specify 0 to get the whole node because that (a) hasn't worked for a bit, (b) is very hard to maintain and (c) I think all the dynamic setting of mins and maxes works just fine.

cleanup this form and submit
