OSC/bc_osc_rstudio_server

.gitlab-ci.yml, packaging/ondemand-bc_osc_rstudio_server.spec
This is a straight copy of the ondemand Gitlab config and I updated the specfile to use the Git tag for versioning.
=> Update CI/CD files

form.yml, template/script.sh.erb
This is ready and works, I'm just waiting a second on whether or not we want to add texlive and/or xalt into the submodule as well.
=> add R 3.6.2 and start using an ondemand submodule for Rstudio

template/before.sh.erb
Workshop materials are versioned, so this will copy the appropriate files to the job directory.
=> version workshop materials

form.js, form.yml
=> add R/4.0.2 module

form.js, form.yml, manifest.yml, submit.yml.erb
Borrowing from the work done on bc_osc_jupyter for the same feature
to merge with pitzer:
- cores change from data attributes defined in the form
- changing the cluster also changes the number of cores
- changing the cluster also chagnes the versions available
=> merge with pitzer

form.js, form.yml, submit.yml.erb
Starting out in draft because we still need to solidify the language.
Note that this does have an edge case where if you leave it blank and request 'a whole node', you'll _always_ request a 48 core node and never a 40 core.
=> merge pitzer-exp into pitzer

CHANGELOG.md, form.js
Trivial changes intended as a test drive.
=> Corrected misspellings.

form.yml.erb, submit.yml.erb
mv account to a select widget with only valid groups as options
=> mv account to a select widget with only valid groups as options

form.yml.erb
rm unused owens-slurm data attributes that were missed when I removed the other owens-slurm items.
=> rm unused owens-slurm data attributes

manifest.yml
simplify the title to get rid of (clusters)
=> simplify the title to get rid of (clusters)

submit.yml.erb
Addresses patches from CVE-2021-33909
=> Update Kubernetes container version

CHANGELOG.md
=> update changelog for v0.19.2

CHANGELOG.md
=> update changelog for v0.19.3

CHANGELOG.md
=> update changelog for v0.19.4

CHANGELOG.md, form.js
hiding an data-option-for element has to be explicitly set. default is to show
=> hiding an data-option-for element has to be explicitly set

submit.yml.erb
Requires https://github.com/OSC/ood_core/pull/317
=> Set cluster label for Kubernetes

submit.yml.erb
This pulls in some new OS packages that Shameema had me install for some newer versions of modules that will be needed to run those modules, I think mostly RStudio.
Image has been pre-pulled to all Kubernetes worker nodes in test and production.
=> Update Kubernetes image

submit.yml.erb
DO NOT MERGE until we know if this solution is needed, just showing as how to run on any node.
=> Run on any Kubernetes node

submit.yml.erb, template/after.sh.erb, template/before.sh.erb, template/bin/auth, template/etc/database.conf, template/etc/logging.conf.erb, template/script.sh.erb, view.html.erb
Most of this is to support CSRF token passing. Others are small enhancements. 
Fixes #34 (actually skips 1.3 :laughing: )
Fixes #79
=> Fixes upgrade issues

template/etc/rsession-profile, template/script.sh.erb
correctly mount modules and /etc/profile.
=> correctly mount modules

README.md
add rserver --help output to readme as a quick reference.
=> add rserver --help output to readme

info.html.erb, template/script.sh.erb
Fix tutorials and expand the language in the card a little bit.
=> Fix tutorials

CHANGELOG.md, form.yml.erb, submit.yml.erb, template/before.sh.erb, template/script.sh.erb
4.1 broke in kubernetes, and this fixes that as much as it can.
It actually disables 4.1 for kubernetes because I can't pass the csrf_token back in kubernetes pending one or both of these issues.
https://github.com/OSC/ood_core/issues/744
https://github.com/OSC/ondemand/issues/1829
=> fix R/4.1 in kubernetes, as much as I can

info.html.erb
=> mistype console

CHANGELOG.md, template/script.sh.erb
Support Apptainer and Singularity
=> Support Apptainer and Singularity

CHANGELOG.md, form.yml.erb, submit.yml.erb, template/script.sh.erb
This adds support for the ascend cluster. Ultimately we ended up using a container instead of using the system installed binary.
=> Support for Ascend

CHANGELOG.md, form.yml.erb
The max for ascend is 88 not 96.
=> max is 88 not 96

form.yml.erb
Fix maxes once again for Ascend. This time for cpuonly jobs.
=> max is only 84 for cpuonly

form.yml.erb
add R/4.3.0 and enable some k8s versions
=> add R/4.3.0 and enable some k8s versions

template/etc/rsession.conf.erb
add rsession.conf and set session timeout to 0
=> add rsession.conf and set session timeout to 0

form.yml.erb, template/before.sh.erb, template/script.sh.erb
=> remove tutorials as an option

submit.yml.erb, template/before.sh.erb, template/script.sh.erb
fix kubernetes clusters because as of right now it doesn't work (even in production)
=> fix kubernetes

form.yml, template/script.sh.erb
=> add support for cardinal

form.yml
remove some versions of R that are being removed from OSC tomorrow. I.e., those modules won't exist soon.
=> remove some versions of R

submit.yml.erb
actually use submit args for cardinal.
=> actually use submit args

form.yml
=> support next gen ascend

form.yml
remove nextgen ascend because the ascend cluster is going to replace it on Monday.
=> remove nextgen ascend

form.yml
fix module selection for ascend
=> fix module selection for ascend
